In [1]:
# difference between numpy array copy and view.
# we will make a copy, change in original array, and display both.

import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = arr.copy()
arr1[0] = 12
print(arr)
print(arr1)

[1 2 3 4 5]
[12  2  3  4  5]


In [2]:
# now we will make a view, change original, display both

import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = arr.view()
arr1[0] = 31
print(arr)
print(arr1)

[31  2  3  4  5]
[31  2  3  4  5]
