In [1]:
# searching array - you can search an array for a certain value and return the indexes that get the match. by using where()
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
arrnew = np.where(arr == 4)
print(arrnew)

(array([3, 5, 6], dtype=int64),)


In [2]:
# now we will find the indexes where the values are even:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.where(arr%2 == 0)
print(arr1)

(array([1, 3, 5, 7], dtype=int64),)


In [3]:
# now we will find the indexes where the values are odd:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.where(arr%2 == 1)
print(arr1)

(array([0, 2, 4, 6], dtype=int64),)


In [4]:
# Searchsorted() - perform binary search in array.
# we will now find the index where the value 7 should be insterted.
import numpy as np
arr = np.array([6,7,8,9])
arr1 = np.searchsorted(arr, 7)
print(arr1)

1


In [5]:
# now we will search fron right side
import numpy as np
arr = np.array([6,7,8,9])
arr1 = np.searchsorted(arr, 7, side='right')
print(arr1)

2


In [6]:
# how to search multiple values:
import numpy as np
arr = np.array([1,3,5,7])
arr1 = np.searchsorted(arr, [2,4,6])
print(arr1)

[1 2 3]
