In [1]:
# Random meaning - something that cannot be predicted logically.
# Now we will generate a random number from 0 to 100
from numpy import random 
arr = random.randint(100)
print(arr) 

61


In [2]:
# You can also genetrate float() via rand() from 0 to 1
from numpy import random 
arr = random.rand()
print(arr) 

0.17593296246765577


In [3]:
# You can also generate random Array.
# we will generate a 1-D array containing 5 random int from 0 to 100:
from numpy import random 
arr = random.randint(100, size=(5))
print(arr) 

[85 76  9 51 69]


In [4]:
# You can also generate random Array.
# we will generate a 2-D array with 3 rows, each row  containing 5 random int from 0 to 100:
from numpy import random 
arr = random.randint(100, size=(3, 5))
print(arr) 

[[ 6 62 31 50 35]
 [36 28 38 49 67]
 [72 45 75 86 54]]


In [5]:
# You can also generate random Array.
# we will generate a 1-D array containing 5 random float:
from numpy import random 
arr = random.rand(5)
print(arr) 

[0.69324813 0.07456161 0.82298672 0.9287897  0.74817227]


In [6]:
# You can also generate random Array.
# we will generate a 2-D array with 3 rows, each containing 5 random float:
from numpy import random 
arr = random.rand(3, 5)
print(arr) 

[[0.712043   0.20956569 0.67615195 0.05521039 0.88882233]
 [0.05835363 0.79018546 0.97072496 0.22424639 0.15716516]
 [0.07982348 0.43832109 0.00625482 0.14019327 0.37134149]]


In [7]:
# you can also generate random numbers from an array
# choice()

from numpy import random 
arr = random.choice([3,5,7,9,1,4,6])
print(arr) 

5


In [8]:
# you can also generate random numbers from an 2-D array
# choice()

from numpy import random 
arr = random.choice([3,5,7,9,1,4,6], size=(3, 5))
print(arr) 

[[6 9 5 1 6]
 [7 7 1 9 3]
 [9 7 3 6 1]]
