In [1]:
# arithemtic operators: +, -, / , *
# by using ufunc additional arguments like, where, dtype and out.
# here now we will use add()
import numpy as np
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
arrnew = np.add(arr1, arr2)
print(arrnew)

[30 32 34 36 38 40]


In [2]:
#  example of substracting the value
import numpy as np
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
arrnew = np.subtract(arr1, arr2)
print(arrnew)

[-10 -10 -10 -10 -10 -10]


In [3]:
# example of multipication
import numpy as np
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
arrnew = np.multiply(arr1, arr2)
print(arrnew)

[200 231 264 299 336 375]


In [4]:
# example of divide()
import numpy as np
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
arrnew = np.divide(arr1, arr2)
print(arrnew)

[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]


In [5]:
# power() function raises the value from the 1st array to the power of the values of the 2nd array and return the results in a new array.

import numpy as np
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([3,5,6,8,2,33])
arrnew = np.power(arr1, arr2)
print(arrnew)

[      1000    3200000  729000000 -520093696       2500          0]


In [6]:
# reminder- mod() and reminder() fucntions return the reminder of the 1st array corrosponding to the 2nd array, and result in the new array.
import numpy as np
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([3,7,9,8,2,33])
arrnew = np.mod(arr1, arr2)
print(arrnew)

[ 1  6  3  0  0 27]


In [7]:
# by using reminder()
import numpy as np
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([3,7,9,8,2,33])
arrnew = np.remainder(arr1, arr2)
print(arrnew)

[ 1  6  3  0  0 27]


In [8]:
# quotient and mod(reminder)
# the divmod() function return both the quotient and mod.
import numpy as np
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([3,7,9,8,2,33])
arrnew = np.divmod(arr1, arr2)
print(arrnew)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [9]:
# absolute() and abs()- do the same operation but here we should use absolute() to avoid confusion with python inbuilt function math.abs().
import numpy as np
arr = np.array([-1,-2,-3,-4,-5])
arrnew = np.absolute(arr)
print(arrnew)

[1 2 3 4 5]
