In [1]:
# Trigonometric function: numpy provides the ufuncs line sin(), cos() and tan() that takes values in radians and produce the corresponding sin, cos and tan values.
# here now we will find the sin value of pi/2
import numpy as np
arr = np.sin(np.pi/2)
print(arr)

1.0


In [2]:
# we will now find the sin values of an array
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
arrnew = np.sin(arr)
print(arrnew)

[1.         0.8660254  0.70710678 0.58778525]


In [3]:
# Convert Degree into radians: by default all of the trigonometric functions tales radians as parameter.
# note: radians values are pi/180* degree value.
# here we will convert all the array values to radians:
import numpy as np
arr = np.array([90, 180, 270,360])
arrnew = np.deg2rad(arr)
print(arrnew)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [4]:
# here we will convert radians into degree.
import numpy as np
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
arrnew = np.rad2deg(arr)
print(arrnew)

[ 90. 180. 270. 360.]


#### Here we can also find angles : arcsin(), arccos() and arctan() that takes values in radians and produce the corresponding sin, cos and tan values.

In [5]:
# we will now find the angle of 1.0
import numpy as np
arr = np.arcsin(1.0)
print(arr)

1.5707963267948966


In [6]:
# angles of each values in an array:
import numpy as np
arr = np.array([1, -1, 0.1])
arrnew = np.arcsin(arr)
print(arrnew)

[ 1.57079633 -1.57079633  0.10016742]


In [7]:
# here we can also find the hypotenous using the pythagoras theorem in numpy
# hypot() function that takes values in radians and produce the corresponding sin, cos and tan values.

In [8]:
# here we will find the hypot for 3 base and 4 perpendicular.
import numpy as np
base = 3
perp = 4
arr = np.hypot(base, perp)
print(arr)

5.0
